export type Word = {
  greek: string;
  en: string;
  es: string;
  rank: number;
};

export const VOCAB_DATA: Word[] = [
  { rank: 1, greek: "ὁ, ἡ, τό", en: "the", es: "el, la, lo" },
  { rank: 2, greek: "καί", en: "and", es: "y" },
  { rank: 3, greek: "αὐτός", en: "self, he/she/it", es: "mismo, él/ella" },
  { rank: 4, greek: "δέ", en: "but, and", es: "pero, y" },
  { rank: 5, greek: "ἐν", en: "in, at", es: "en" },
  { rank: 6, greek: "γάρ", en: "for", es: "porque, pues" },
  { rank: 7, greek: "εἰμί", en: "to be", es: "ser, estar" },
  { rank: 8, greek: "οὗτος", en: "this", es: "este, esta" },
  { rank: 9, greek: "μή", en: "not", es: "no" },
  { rank: 10, greek: "λέγω", en: "to say, speak", es: "decir, hablar" },
  { rank: 11, greek: "εἰς", en: "into", es: "hacia, en" },
  { rank: 12, greek: "οὐ", en: "not", es: "no" },
  { rank: 13, greek: "ὅς", en: "who, which", es: "quien, el cual" },
  { rank: 14, greek: "πᾶς", en: "all, every", es: "todo, cada" },
  { rank: 15, greek: "σύ", en: "you", es: "tú" },
  { rank: 16, greek: "ἄν", en: "modal particle", es: "partícula modal" },
  { rank: 17, greek: "τίς", en: "who? which?", es: "quién? cuál?" },
  { rank: 18, greek: "ἐγώ", en: "I", es: "yo" },
  { rank: 19, greek: "ἐπί", en: "on, upon", es: "sobre, en" },
  { rank: 20, greek: "ποιέω", en: "to do, make", es: "hacer" },
  { rank: 21, greek: "κατά", en: "down, according to", es: "hacia abajo, según" },
  { rank: 22, greek: "μετά", en: "with, after", es: "con, después de" },
  { rank: 23, greek: "ὁράω", en: "to see", es: "ver" },
  { rank: 24, greek: "ἀκούω", en: "to hear", es: "oír, escuchar" },
  { rank: 25, greek: "πρός", en: "towards", es: "hacia, junto a" },
  { rank: 26, greek: "γíγνομαι", en: "to become", es: "llegar a ser" },
  { rank: 27, greek: "διά", en: "through, because of", es: "a través de, por" },
  { rank: 28, greek: "ἔχω", en: "to have, hold", es: "tener" },
  { rank: 29, greek: "δίδωμι", en: "to give", es: "dar" },
  { rank: 30, greek: "πολύς", en: "much, many", es: "mucho" },
  { rank: 31, greek: "περί", en: "about, concerning", es: "acerca de, sobre" },
  { rank: 32, greek: "ἔρχομαι", en: "to come, go", es: "venir, ir" },
  { rank: 33, greek: "ποίημα", en: "work, creation", es: "obra, creación" },
  { rank: 34, greek: "ἄλλος", en: "other, another", es: "otro" },
  { rank: 35, greek: "ἀπό", en: "from, away from", es: "de, desde" },
  { rank: 36, greek: "θεός", en: "god", es: "dios" },
  { rank: 37, greek: "ἵνα", en: "in order that", es: "para que" },
  { rank: 38, greek: "πρό", en: "before", es: "antes de, delante de" },
  { rank: 39, greek: "ὥστε", en: "so that", es: "de modo que" },
  { rank: 40, greek: "παρά", en: "beside, from", es: "junto a, de parte de" },
  { rank: 41, greek: "γε", en: "at least, indeed", es: "al menos, en verdad" },
  { rank: 42, greek: "ὑπό", en: "under, by", es: "bajo, por" },
  { rank: 43, greek: "τις", en: "someone, something", es: "alguien, algo" },
  { rank: 44, greek: "λαμβάνω", en: "to take, receive", es: "tomar, recibir" },
  { rank: 45, greek: "οὖν", en: "therefore, then", es: "por tanto, pues" },
  { rank: 46, greek: "μεγάς", en: "great, large", es: "grande" },
  { rank: 47, greek: "ἐάν", en: "if", es: "si" },
  { rank: 48, greek: "γινώσκω", en: "to know", es: "conocer, saber" },
  { rank: 49, greek: "ἀνήρ", en: "man, husband", es: "hombre, marido" },
  { rank: 50, greek: "ἄνθρωπος", en: "human, person", es: "ser humano, persona" },
  { rank: 51, greek: "φημί", en: "to say", es: "decir" },
  { rank: 52, greek: "εἷς", en: "one", es: "uno" },
  { rank: 53, greek: "μέν", en: "on the one hand", es: "por una parte" },
  { rank: 54, greek: "ὁδός", en: "way, road", es: "camino" },
  { rank: 55, greek: "χείρ", en: "hand", es: "mano" },
  { rank: 56, greek: "ψυχή", en: "soul, life", es: "alma, vida" },
  { rank: 57, greek: "καλός", en: "beautiful, good", es: "bello, bueno" },
  { rank: 58, greek: "δύναμαι", en: "to be able", es: "poder" },
  { rank: 59, greek: "πρῶτος", en: "first", es: "primero" },
  { rank: 60, greek: "ἀγάπη", en: "love", es: "amor" },
  { rank: 61, greek: "νῦν", en: "now", es: "ahora" },
  { rank: 62, greek: "ὄνομα", en: "name", es: "nombre" },
  { rank: 63, greek: "πατήρ", en: "father", es: "padre" },
  { rank: 64, greek: "πνεῦμα", en: "spirit, wind", es: "espíritu, viento" },
  { rank: 65, greek: "ἀδελφός", en: "brother", es: "hermano" },
  { rank: 66, greek: "λόγος", en: "word, reason", es: "palabra, razón" },
  { rank: 67, greek: "μήτηρ", en: "mother", es: "madre" },
  { rank: 68, greek: "οὐρανός", en: "heaven, sky", es: "cielo" },
  { rank: 69, greek: "ἐκ", en: "out of, from", es: "de, desde dentro" },
  { rank: 70, greek: "πίστις", en: "faith, trust", es: "fe, confianza" },
  { rank: 71, greek: "κύριος", en: "lord, master", es: "señor" },
  { rank: 72, greek: "ἔργον", en: "work, deed", es: "obra, hecho" },
  { rank: 73, greek: "ἡμέρα", en: "day", es: "día" },
  { rank: 74, greek: "πόλις", en: "city", es: "ciudad" },
  { rank: 75, greek: "βασιλεία", en: "kingdom", es: "reino" },
  { rank: 76, greek: "μαθητής", en: "disciple, student", es: "discípulo, estudiante" },
  { rank: 77, greek: "κόσμος", en: "world, order", es: "mundo, orden" },
  { rank: 78, greek: "υἱός", en: "son", es: "hijo" },
  { rank: 79, greek: "χάρις", en: "grace", es: "gracia" },
  { rank: 80, greek: "σάρξ", en: "flesh", es: "carne" },
  { rank: 81, greek: "ἐκεῖνος", en: "that", es: "aquel, aquello" },
  { rank: 82, greek: "ἑαυτοῦ", en: "of himself, herself", es: "de sí mismo" },
  { rank: 83, greek: "ἀλλά", en: "but", es: "pero, sino" },
  { rank: 84, greek: "ἤ", en: "or, than", es: "o, que" },
  { rank: 85, greek: "νόμος", en: "law", es: "ley" },
  { rank: 86, greek: "καρδία", en: "heart", es: "corazón" },
  { rank: 87, greek: "γυνή", en: "woman, wife", es: "mujer, esposa" },
  { rank: 88, greek: "δοῦλος", en: "slave", es: "esclavo" },
  { rank: 89, greek: "φῶς", en: "light", es: "luz" },
  { rank: 90, greek: "ὕδωρ", en: "water", es: "agua" },
  { rank: 91, greek: "πῦρ", en: "fire", es: "fuego" },
  { rank: 92, greek: "ζωή", en: "life", es: "vida" },
  { rank: 93, greek: "θάνατος", en: "death", es: "muerte" },
  { rank: 94, greek: "δύο", en: "two", es: "dos" },
  { rank: 95, greek: "τρεῖς", en: "three", es: "tres" },
  { rank: 96, greek: "τέσσαρες", en: "four", es: "cuatro" },
  { rank: 97, greek: "πέντε", en: "five", es: "cinco" },
  { rank: 98, greek: "δέκα", en: "ten", es: "diez" },
  { rank: 99, greek: "ἕκατον", en: "hundred", es: "cien" },
  { rank: 100, greek: "χίλιοι", en: "thousand", es: "mil" },
  // Adding more words to reach 500
  { rank: 101, greek: "ἀγαθός", en: "good", es: "bueno" },
  { rank: 102, greek: "ἀγάπη", en: "love", es: "amor" },
  { rank: 103, greek: "ἄγγελος", en: "messenger, angel", es: "mensajero, ángel" },
  { rank: 104, greek: "ἅγιος", en: "holy", es: "santo" },
  { rank: 105, greek: "ἀγορά", en: "marketplace", es: "ágora, mercado" },
  { rank: 106, greek: "ἀγρός", en: "field", es: "campo" },
  { rank: 107, greek: "ἄγω", en: "to lead, bring", es: "conducir, traer" },
  { rank: 108, greek: "ἀγών", en: "struggle, contest", es: "lucha, certamen" },
  { rank: 109, greek: "αἷμα", en: "blood", es: "sangre" },
  { rank: 110, greek: "αἴρω", en: "to lift, take away", es: "levantar, quitar" },
  { rank: 111, greek: "αἰτέω", en: "to ask", es: "pedir" },
  { rank: 112, greek: "αἰών", en: "age, eternity", es: "era, eternidad" },
  { rank: 113, greek: "ἀλήθεια", en: "truth", es: "verdad" },
  { rank: 114, greek: "ἁμαρτία", en: "sin", es: "pecado" },
  { rank: 115, greek: "ἀμήν", en: "amen, truly", es: "amén, verdaderamente" },
  { rank: 116, greek: "ἀμνός", en: "lamb", es: "cordero" },
  { rank: 117, greek: "ἄνεμος", en: "wind", es: "viento" },
  { rank: 118, greek: "ἀνοίγω", en: "to open", es: "abrir" },
  { rank: 119, greek: "ἄξιος", en: "worthy", es: "digno" },
  { rank: 120, greek: "ἀπαγγέλλω", en: "to announce", es: "anunciar" },
  { rank: 121, greek: "ἀπέρχομαι", en: "to go away", es: "irse" },
  { rank: 122, greek: "ἀπόστολος", en: "apostle, messenger", es: "apóstol, mensajero" },
  { rank: 123, greek: "ἄρτος", en: "bread", es: "pan" },
  { rank: 124, greek: "ἀρχή", en: "beginning, rule", es: "principio, mando" },
  { rank: 125, greek: "ἀρχιερεύς", en: "high priest", es: "sumo sacerdote" },
  { rank: 126, greek: "ἄρχω", en: "to rule, begin", es: "mandar, empezar" },
  { rank: 127, greek: "ἀσπάζομαι", en: "to greet", es: "saludar" },
  { rank: 128, greek: "αὐλή", en: "courtyard", es: "patio" },
  { rank: 129, greek: "ἀφίημι", en: "to let go, forgive", es: "dejar, perdonar" },
  { rank: 130, greek: "βάλλω", en: "to throw, put", es: "lanzar, poner" },
  { rank: 131, greek: "βαπτίζω", en: "to baptize", es: "bautizar" },
  { rank: 132, greek: "βιβλίον", en: "book", es: "libro" },
  { rank: 133, greek: "βλασφημέω", en: "to blaspheme", es: "blasfemar" },
  { rank: 134, greek: "βλέπω", en: "to see", es: "ver" },
  { rank: 135, greek: "βοάω", en: "to cry out", es: "gritar" },
  { rank: 136, greek: "βουλή", en: "council, plan", es: "consejo, plan" },
  { rank: 137, greek: "βούλομαι", en: "to wish, want", es: "querer" },
  { rank: 138, greek: "γάμος", en: "marriage", es: "matrimonio" },
  { rank: 139, greek: "γενεά", en: "generation", es: "generación" },
  { rank: 140, greek: "γένος", en: "race, kind", es: "raza, género" },
  { rank: 141, greek: "γῆ", en: "earth, land", es: "tierra" },
  { rank: 142, greek: "γλῶσσα", en: "tongue, language", es: "lengua" },
  { rank: 143, greek: "γραμματεύς", en: "scribe", es: "escriba" },
  { rank: 144, greek: "γραφή", en: "writing, scripture", es: "escritura" },
  { rank: 145, greek: "γράφω", en: "to write", es: "escribir" },
  { rank: 146, greek: "δαιμόνιον", en: "demon", es: "demonio" },
  { rank: 147, greek: "δάκρυον", en: "tear", es: "lágrima" },
  { rank: 148, greek: "δεῖ", en: "it is necessary", es: "es necesario" },
  { rank: 149, greek: "δείκνυμι", en: "to show", es: "mostrar" },
  { rank: 150, greek: "δεῖπνον", en: "supper, dinner", es: "cena" },
  { rank: 151, greek: "δέχομαι", en: "to receive", es: "recibir" },
  { rank: 152, greek: "δέω", en: "to bind, tie", es: "atar" },
  { rank: 153, greek: "δηλόω", en: "to make clear", es: "aclarar" },
  { rank: 154, greek: "διδάσκαλος", en: "teacher", es: "maestro" },
  { rank: 155, greek: "διδάσκω", en: "to teach", es: "enseñar" },
  { rank: 156, greek: "δίκαιος", en: "righteous, just", es: "justo" },
  { rank: 157, greek: "δικαιοσύνη", en: "righteousness", es: "justicia" },
  { rank: 158, greek: "διώκω", en: "to pursue, persecute", es: "perseguir" },
  { rank: 159, greek: "δοκέω", en: "to think, seem", es: "parecer" },
  { rank: 160, greek: "δόξα", en: "glory", es: "gloria" },
  { rank: 161, greek: "δοξάζω", en: "to glorify", es: "glorificar" },
  { rank: 162, greek: "δύναμις", en: "power", es: "poder" },
  { rank: 163, greek: "δυνατός", en: "powerful, able", es: "poderoso, capaz" },
  { rank: 164, greek: "δῶρον", en: "gift", es: "regalo" },
  { rank: 165, greek: "ἔθνος", en: "nation, Gentile", es: "nación, gentil" },
  { rank: 166, greek: "ἔθος", en: "custom", es: "costumbre" },
  { rank: 167, greek: "εἶδος", en: "form, appearance", es: "forma, apariencia" },
  { rank: 168, greek: "εἴδωλον", en: "idol", es: "ídolo" },
  { rank: 169, greek: "εἰρήνη", en: "peace", es: "paz" },
  { rank: 170, greek: "ἐλπίς", en: "hope", es: "esperanza" },
  { rank: 171, greek: "ἔμπροσθεν", en: "before, in front of", es: "delante de" },
  { rank: 172, greek: "ἐντολή", en: "commandment", es: "mandamiento" },
  { rank: 173, greek: "ἐνώπιον", en: "before, in the presence of", es: "ante" },
  { rank: 174, greek: "ἐξουσία", en: "authority, power", es: "autoridad" },
  { rank: 175, greek: "ἔξω", en: "outside", es: "fuera" },
  { rank: 176, greek: "ἑορτή", en: "festival", es: "fiesta" },
  { rank: 177, greek: "ἐπαγγελία", en: "promise", es: "promesa" },
  { rank: 178, greek: "ἐπερωτάω", en: "to ask, question", es: "preguntar" },
  { rank: 179, greek: "ἐπιγινώσκω", en: "to recognize, know", es: "reconocer" },
  { rank: 180, greek: "ἐπιθυμία", en: "desire, lust", es: "deseo" },
  { rank: 181, greek: "ἐπιστολή", en: "letter", es: "carta" },
  { rank: 182, greek: "ἑπτά", en: "seven", es: "siete" },
  { rank: 183, greek: "ἐργάζομαι", en: "to work", es: "trabajar" },
  { rank: 184, greek: "ἔρημος", en: "desert, wilderness", es: "desierto" },
  { rank: 185, greek: "ἐσθίω", en: "to eat", es: "comer" },
  { rank: 186, greek: "ἔσχατος", en: "last", es: "último" },
  { rank: 187, greek: "ἕτερος", en: "other, different", es: "otro, diferente" },
  { rank: 188, greek: "ἔτι", en: "still, yet", es: "todavía, aún" },
  { rank: 189, greek: "ἑτοιμάζω", en: "to prepare", es: "preparar" },
  { rank: 190, greek: "ἔτος", en: "year", es: "año" },
  { rank: 191, greek: "εὐαγγελίζω", en: "to preach the gospel", es: "evangelizar" },
  { rank: 192, greek: "εὐαγγέλιον", en: "gospel", es: "evangelio" },
  { rank: 193, greek: "εὐθύς", en: "immediately", es: "inmediatamente" },
  { rank: 194, greek: "εὐλογέω", en: "to bless", es: "bendecir" },
  { rank: 195, greek: "εὑρίσκω", en: "to find", es: "hallar" },
  { rank: 196, greek: "εὐχαριστέω", en: "to give thanks", es: "agradecer" },
  { rank: 197, greek: "ἐχθρός", en: "enemy", es: "enemigo" },
  { rank: 198, greek: "ἕως", en: "until, while", es: "hasta" },
  { rank: 199, greek: "ζάω", en: "to live", es: "vivir" },
  { rank: 200, greek: "ζητέω", en: "to seek", es: "buscar" },
  { rank: 201, greek: "θάλασσα", en: "sea", es: "mar" },
  { rank: 202, greek: "θέλημα", en: "will", es: "voluntad" },
  { rank: 203, greek: "θέλω", en: "to will, wish", es: "querer" },
  { rank: 204, greek: "θεραπεύω", en: "to heal", es: "sanar" },
  { rank: 205, greek: "θεωρέω", en: "to behold, see", es: "contemplar" },
  { rank: 206, greek: "θηρίον", en: "beast, wild animal", es: "fiera" },
  { rank: 207, greek: "θλῖψις", en: "tribulation, affliction", es: "tribulación" },
  { rank: 208, greek: "θρόνος", en: "throne", es: "trono" },
  { rank: 209, greek: "θύρα", en: "door", es: "puerta" },
  { rank: 210, greek: "θυσία", en: "sacrifice", es: "sacrificio" },
  { rank: 211, greek: "ἴδιος", en: "one's own", es: "propio" },
  { rank: 212, greek: "ἰδού", en: "behold!", es: "¡he aquí!" },
  { rank: 213, greek: "ἱερεύς", en: "priest", es: "sacerdote" },
  { rank: 214, greek: "ἱερόν", en: "temple", es: "templo" },
  { rank: 215, greek: "ἱκανός", en: "sufficient, able", es: "suficiente" },
  { rank: 216, greek: "ἱμάτιον", en: "garment", es: "vestidura" },
  { rank: 217, greek: "ἵστημι", en: "to stand", es: "estar en pie" },
  { rank: 218, greek: "ἰσχυρός", en: "strong", es: "fuerte" },
  { rank: 219, greek: "ἰχθύς", en: "fish", es: "pez" },
  { rank: 220, greek: "καθαρίζω", en: "to cleanse", es: "limpiar" },
  { rank: 221, greek: "κάθημαι", en: "to sit", es: "sentarse" },
  { rank: 222, greek: "καθίζω", en: "to sit down", es: "sentar" },
  { rank: 223, greek: "καθώς", en: "as, just as", es: "como" },
  { rank: 224, greek: "καινός", en: "new", es: "nuevo" },
  { rank: 225, greek: "καιρός", en: "time, season", es: "tiempo, sazón" },
  { rank: 226, greek: "κακός", en: "bad, evil", es: "malo" },
  { rank: 227, greek: "καλέω", en: "to call", es: "llamar" },
  { rank: 228, greek: "καυχάομαι", en: "to boast", es: "gloriarse" },
  { rank: 229, greek: "κεφαλή", en: "head", es: "cabeza" },
  { rank: 230, greek: "κηρύσσω", en: "to proclaim", es: "proclamar" },
  { rank: 231, greek: "κλαίω", en: "to weep", es: "llorar" },
  { rank: 232, greek: "κλάδος", en: "branch", es: "rama" },
  { rank: 233, greek: "κλείω", en: "to shut", es: "cerrar" },
  { rank: 234, greek: "κλέπτης", en: "thief", es: "ladrón" },
  { rank: 235, greek: "κληρονομέω", en: "to inherit", es: "heredar" },
  { rank: 236, greek: "κλίνη", en: "bed", es: "lecho" },
  { rank: 237, greek: "κοιλία", en: "belly, womb", es: "vientre" },
  { rank: 238, greek: "κοιμάομαι", en: "to sleep", es: "dormir" },
  { rank: 239, greek: "κοινός", en: "common", es: "común" },
  { rank: 240, greek: "κοινωνία", en: "fellowship", es: "comunión" },
  { rank: 241, greek: "κόπος", en: "labor, trouble", es: "fatiga" },
  { rank: 242, greek: "κοπιάω", en: "to toil", es: "fatigarse" },
  { rank: 243, greek: "κόφινος", en: "basket", es: "cesta" },
  { rank: 244, greek: "κράζω", en: "to cry out", es: "gritar" },
  { rank: 245, greek: "κρατέω", en: "to seize, hold", es: "asir" },
  { rank: 246, greek: "κράτιστος", en: "most excellent", es: "excelentísimo" },
  { rank: 247, greek: "κρεμάννυμι", en: "to hang", es: "colgar" },
  { rank: 248, greek: "κρίνω", en: "to judge", es: "juzgar" },
  { rank: 249, greek: "κρίσις", en: "judgment", es: "juicio" },
  { rank: 250, greek: "κριτής", en: "judge", es: "juez" },
  { rank: 251, greek: "κρύπτω", en: "to hide", es: "esconder" },
  { rank: 252, greek: "κτίζω", en: "to create", es: "crear" },
  { rank: 253, greek: "κώμη", en: "village", es: "aldea" },
  { rank: 254, greek: "κωφός", en: "deaf, dumb", es: "sordo, mudo" },
  { rank: 255, greek: "λαλέω", en: "to speak", es: "hablar" },
  { rank: 256, greek: "λάμπω", en: "to shine", es: "brillar" },
  { rank: 257, greek: "λαός", en: "people", es: "pueblo" },
  { rank: 258, greek: "λατρεύω", en: "to serve, worship", es: "servir" },
  { rank: 259, greek: "λείπω", en: "to leave, lack", es: "dejar, faltar" },
  { rank: 260, greek: "λευκός", en: "white", es: "blanco" },
  { rank: 261, greek: "λιμήν", en: "harbor, haven", es: "puerto" },
  { rank: 262, greek: "λίμνη", en: "lake", es: "lago" },
  { rank: 263, greek: "λιμός", en: "hunger, famine", es: "hambre" },
  { rank: 264, greek: "λίθος", en: "stone", es: "piedra" },
  { rank: 265, greek: "λύκος", en: "wolf", es: "lobo" },
  { rank: 266, greek: "λυπέω", en: "to grieve", es: "contristar" },
  { rank: 267, greek: "λύπη", en: "grief, sorrow", es: "tristeza" },
  { rank: 268, greek: "λύω", en: "to loose, destroy", es: "desatar" },
  { rank: 269, greek: "μακάριος", en: "blessed", es: "bienaventurado" },
  { rank: 270, greek: "μανθάνω", en: "to learn", es: "aprender" },
  { rank: 271, greek: "μαρτυρέω", en: "to bear witness", es: "testificar" },
  { rank: 272, greek: "μαρτυρία", en: "testimony", es: "testimonio" },
  { rank: 273, greek: "μάρτυς", en: "witness", es: "testigo" },
  { rank: 274, greek: "μάστιξ", en: "whip, plague", es: "azote" },
  { rank: 275, greek: "μάχη", en: "battle, fight", es: "combate" },
  { rank: 276, greek: "μέγας", en: "great", es: "grande" },
  { rank: 277, greek: "μέθη", en: "drunkenness", es: "embriaguez" },
  { rank: 278, greek: "μείζων", en: "greater", es: "mayor" },
  { rank: 279, greek: "μέλας", en: "black", es: "negro" },
  { rank: 280, greek: "μέλει", en: "it is a care", es: "importar" },
  { rank: 281, greek: "μέλλω", en: "to be about to", es: "ir a" },
  { rank: 282, greek: "μέλος", en: "member, limb", es: "miembro" },
  { rank: 283, greek: "μένω", en: "to remain", es: "permanecer" },
  { rank: 284, greek: "μερίς", en: "part, portion", es: "parte" },
  { rank: 285, greek: "μέρος", en: "part, share", es: "parte" },
  { rank: 286, greek: "μέσος", en: "middle", es: "medio" },
  { rank: 287, greek: "μετάνοια", en: "repentance", es: "arrepentimiento" },
  { rank: 288, greek: "μέτρον", en: "measure", es: "medida" },
  { rank: 289, greek: "μέτωπον", en: "forehead", es: "frente" },
  { rank: 290, greek: "μέχρι", en: "until", es: "hasta" },
  { rank: 291, greek: "μιαίνω", en: "to stain, defile", es: "manchar" },
  { rank: 292, greek: "μικρός", en: "small, little", es: "pequeño" },
  { rank: 293, greek: "μιμνήσκομαι", en: "to remember", es: "recordar" },
  { rank: 294, greek: "μισέω", en: "to hate", es: "odiar" },
  { rank: 295, greek: "μισθός", en: "reward, wages", es: "recompensa" },
  { rank: 296, greek: "μνῆμα", en: "grave, tomb", es: "sepulcro" },
  { rank: 297, greek: "μοιχεία", en: "adultery", es: "adulterio" },
  { rank: 298, greek: "μόνος", en: "alone, only", es: "solo" },
  { rank: 299, greek: "μονή", en: "dwelling, room", es: "morada" },
  { rank: 300, greek: "μορφή", en: "form, shape", es: "forma" },
  { rank: 301, greek: "μύρον", en: "ointment", es: "ungüento" },
  { rank: 302, greek: "μυστήριον", en: "mystery", es: "misterio" },
  { rank: 303, greek: "μωρός", en: "foolish", es: "necio" },
  { rank: 304, greek: "ναός", en: "temple, sanctuary", es: "santuario" },
  { rank: 305, greek: "νεανίας", en: "young man", es: "joven" },
  { rank: 306, greek: "νεκρός", en: "dead", es: "muerto" },
  { rank: 307, greek: "νέος", en: "new, young", es: "nuevo, joven" },
  { rank: 308, greek: "νεφέλη", en: "cloud", es: "nube" },
  { rank: 309, greek: "νήπιος", en: "infant, child", es: "niño" },
  { rank: 310, greek: "νηστεύω", en: "to fast", es: "ayunar" },
  { rank: 311, greek: "νῆσος", en: "island", es: "isla" },
  { rank: 312, greek: "νικάω", en: "to conquer", es: "vencer" },
  { rank: 313, greek: "νίκη", en: "victory", es: "victoria" },
  { rank: 314, greek: "νίπτω", en: "to wash", es: "lavar" },
  { rank: 315, greek: "νοέω", en: "to understand", es: "entender" },
  { rank: 316, greek: "νομή", en: "pasture", es: "pasto" },
  { rank: 317, greek: "νόμος", en: "law", es: "ley" },
  { rank: 318, greek: "νόσος", en: "disease", es: "enfermedad" },
  { rank: 319, greek: "νοῦς", en: "mind, understanding", es: "mente" },
  { rank: 320, greek: "νύμφη", en: "bride", es: "novia" },
  { rank: 321, greek: "νυμφίος", en: "bridegroom", es: "novio" },
  { rank: 322, greek: "νύξ", en: "night", es: "noche" },
  { rank: 323, greek: "νῶτος", en: "back", es: "espalda" },
  { rank: 324, greek: "ξένος", en: "stranger, host", es: "extraño" },
  { rank: 325, greek: "ξηρός", en: "dry", es: "seco" },
  { rank: 326, greek: "ξύλον", en: "wood, tree", es: "madera" },
  { rank: 327, greek: "ὅδε", en: "this", es: "este" },
  { rank: 328, greek: "ὀδούς", en: "tooth", es: "diente" },
  { rank: 329, greek: "ὀδύνη", en: "pain, sorrow", es: "dolor" },
  { rank: 330, greek: "οἶκος", en: "house", es: "casa" },
  { rank: 331, greek: "οἶνος", en: "wine", es: "vino" },
  { rank: 332, greek: "ὅλος", en: "whole, all", es: "todo" },
  { rank: 333, greek: "ὄμνυμι", en: "to swear", es: "jurar" },
  { rank: 334, greek: "ὁμολογέω", en: "to confess", es: "confesar" },
  { rank: 335, greek: "ὄναρ", en: "dream", es: "sueño" },
  { rank: 336, greek: "ὄνειδος", en: "reproach", es: "reproche" },
  { rank: 337, greek: "ὄνομα", en: "name", es: "nombre" },
  { rank: 338, greek: "ὀξύς", en: "sharp, swift", es: "agudo" },
  { rank: 339, greek: "ὅπλον", en: "weapon", es: "arma" },
  { rank: 340, greek: "ὅπου", en: "where", es: "donde" },
  { rank: 341, greek: "ὀργή", en: "anger, wrath", es: "ira" },
  { rank: 342, greek: "ὄρος", en: "mountain", es: "monte" },
  { rank: 343, greek: "ὅσος", en: "as great as", es: "cuanto" },
  { rank: 344, greek: "ὅστις", en: "whoever", es: "quienquiera" },
  { rank: 345, greek: "ὀσμή", en: "odor", es: "olor" },
  { rank: 346, greek: "ὅταν", en: "whenever", es: "cuando" },
  { rank: 347, greek: "ὅτε", en: "when", es: "cuando" },
  { rank: 348, greek: "ὅτι", en: "that, because", es: "que, porque" },
  { rank: 349, greek: "οὐδέ", en: "and not, nor", es: "ni" },
  { rank: 350, greek: "οὐδείς", en: "no one, nothing", es: "nadie" },
  { rank: 351, greek: "οὐκέτι", en: "no longer", es: "ya no" },
  { rank: 352, greek: "οὖν", en: "therefore", es: "por tanto" },
  { rank: 353, greek: "οὔτε", en: "neither, nor", es: "ni... ni" },
  { rank: 354, greek: "οὗτος", en: "this", es: "este" },
  { rank: 355, greek: "οὕτως", en: "thus", es: "así" },
  { rank: 356, greek: "ὀφειλέτης", en: "debtor", es: "deudor" },
  { rank: 357, greek: "ὀφθαλμός", en: "eye", es: "ojo" },
  { rank: 358, greek: "ὄφις", en: "serpent", es: "serpiente" },
  { rank: 359, greek: "ὄχλος", en: "crowd", es: "muchedumbre" },
  { rank: 360, greek: "ὀψία", en: "evening", es: "tarde" },
  { rank: 361, greek: "πάθος", en: "suffering, passion", es: "pasión" },
  { rank: 362, greek: "παιδίον", en: "little child", es: "niñito" },
  { rank: 363, greek: "παῖς", en: "child", es: "niño" },
  { rank: 364, greek: "παλαιός", en: "old", es: "viejo" },
  { rank: 365, greek: "πάλιν", en: "again", es: "otra vez" },
  { rank: 366, greek: "παντούς", en: "every, all", es: "todo" },
  { rank: 367, greek: "παρά", en: "beside, from", es: "de parte de" },
  { rank: 368, greek: "παραβολή", en: "parable", es: "parábola" },
  { rank: 369, greek: "παράδοσις", en: "tradition", es: "tradición" },
  { rank: 370, greek: "παραλαμβάνω", en: "to receive", es: "recibir" },
  { rank: 371, greek: "παράκλητος", en: "advocate, comforter", es: "paráclito" },
  { rank: 372, greek: "παραστίθημι", en: "to set before", es: "presentar" },
  { rank: 373, greek: "παρθένος", en: "virgin", es: "virgen" },
  { rank: 374, greek: "παρίστημι", en: "to present", es: "presentar" },
  { rank: 375, greek: "παρουσία", en: "presence, coming", es: "presencia" },
  { rank: 376, greek: "πᾶς", en: "all, every", es: "todo" },
  { rank: 377, greek: "πάσχα", en: "passover", es: "pascua" },
  { rank: 378, greek: "πάσχω", en: "to suffer", es: "sufrir" },
  { rank: 379, greek: "πατήρ", en: "father", es: "padre" },
  { rank: 380, greek: "πατρίς", en: "fatherland", es: "patria" },
  { rank: 381, greek: "παύω", en: "to stop", es: "cesar" },
  { rank: 382, greek: "πείθω", en: "to persuade", es: "persuadir" },
  { rank: 383, greek: "πεινάω", en: "to hunger", es: "tener hambre" },
  { rank: 384, greek: "πειρασμός", en: "temptation", es: "tentación" },
  { rank: 385, greek: "πέμπω", en: "to send", es: "enviar" },
  { rank: 386, greek: "πενθέω", en: "to mourn", es: "llorar" },
  { rank: 387, greek: "πένης", en: "poor", es: "pobre" },
  { rank: 388, greek: "περί", en: "about, around", es: "alrededor" },
  { rank: 389, greek: "περισσότερος", en: "greater, more", es: "más abundante" },
  { rank: 390, greek: "περιστερά", en: "dove", es: "paloma" },
  { rank: 391, greek: "περιτέμνω", en: "to circumcise", es: "circuncidar" },
  { rank: 392, greek: "πέτρα", en: "rock", es: "piedra" },
  { rank: 393, greek: "πηγή", en: "spring, fountain", es: "fuente" },
  { rank: 394, greek: "πιάζω", en: "to seize", es: "asir" },
  { rank: 395, greek: "πίνω", en: "to drink", es: "beber" },
  { rank: 396, greek: "πίπτω", en: "to fall", es: "caer" },
  { rank: 397, greek: "πιστεύω", en: "to believe", es: "creer" },
  { rank: 398, greek: "πίστις", en: "faith", es: "fe" },
  { rank: 399, greek: "πιστός", en: "faithful", es: "fiel" },
  { rank: 400, greek: "πλανάω", en: "to deceive", es: "engañar" },
  { rank: 401, greek: "πλάνος", en: "deceitful, deceiver", es: "engañoso" },
  { rank: 402, greek: "πλατεῖα", en: "street", es: "plaza" },
  { rank: 403, greek: "πλέω", en: "to sail", es: "navegar" },
  { rank: 404, greek: "πλήρης", en: "full", es: "lleno" },
  { rank: 405, greek: "πληρόω", en: "to fill", es: "llenar" },
  { rank: 406, greek: "πλοῖον", en: "boat", es: "barca" },
  { rank: 407, greek: "πλούσιος", en: "rich", es: "rico" },
  { rank: 408, greek: "πλοῦτος", en: "wealth", es: "riqueza" },
  { rank: 409, greek: "πνεῦμα", en: "spirit", es: "espíritu" },
  { rank: 410, greek: "ποιέω", en: "to do, make", es: "hacer" },
  { rank: 411, greek: "ποιμήν", en: "shepherd", es: "pastor" },
  { rank: 412, greek: "ποῖος", en: "what sort of?", es: "¿cuál?" },
  { rank: 413, greek: "πόλις", en: "city", es: "ciudad" },
  { rank: 414, greek: "πολλάκις", en: "often", es: "muchas veces" },
  { rank: 415, greek: "πολύς", en: "much, many", es: "mucho" },
  { rank: 416, greek: "πονηρός", en: "evil, wicked", es: "malo" },
  { rank: 417, greek: "πορεύομαι", en: "to go", es: "ir" },
  { rank: 418, greek: "πόρνη", en: "prostitute", es: "prostituta" },
  { rank: 419, greek: "πόρνος", en: "fornicator", es: "fornicario" },
  { rank: 420, greek: "πόσος", en: "how much?", es: "¿cuánto?" },
  { rank: 421, greek: "ποταμός", en: "river", es: "río" },
  { rank: 422, greek: "ποτέ", en: "once, ever", es: "alguna vez" },
  { rank: 423, greek: "ποῦ", en: "where?", es: "¿dónde?" },
  { rank: 424, greek: "πούς", en: "foot", es: "pie" },
  { rank: 425, greek: "πρᾶγμα", en: "thing, deed", es: "cosa" },
  { rank: 426, greek: "πραΰς", en: "gentle, meek", es: "manso" },
  { rank: 427, greek: "πράσσω", en: "to do, practice", es: "practicar" },
  { rank: 428, greek: "πρεσβύτερος", en: "elder", es: "anciano" },
  { rank: 429, greek: "πρίν", en: "before", es: "antes" },
  { rank: 430, greek: "πρό", en: "before", es: "delante" },
  { rank: 431, greek: "πρόβατον", en: "sheep", es: "oveja" },
  { rank: 432, greek: "πρός", en: "towards", es: "hacia" },
  { rank: 433, greek: "προσεύχομαι", en: "to pray", es: "orar" },
  { rank: 434, greek: "προσευχή", en: "prayer", es: "oración" },
  { rank: 435, greek: "προσφέρω", en: "to offer", es: "ofrecer" },
  { rank: 436, greek: "πρόσωπον", en: "face", es: "rostro" },
  { rank: 437, greek: "προφήτης", en: "prophet", es: "profeta" },
  { rank: 438, greek: "πρῶτος", en: "first", es: "primero" },
  { rank: 439, greek: "πτωχός", en: "poor", es: "pobre" },
  { rank: 440, greek: "πύλη", en: "gate", es: "puerta" },
  { rank: 441, greek: "πυνθάνομαι", en: "to inquire", es: "preguntar" },
  { rank: 442, greek: "πῦρ", en: "fire", es: "fuego" },
  { rank: 443, greek: "πῶς", en: "how?", es: "¿cómo?" },
  { rank: 444, greek: "ῥῆμα", en: "word, saying", es: "palabra" },
  { rank: 445, greek: "ῥίζα", en: "root", es: "raíz" },
  { rank: 446, greek: "ῥύομαι", en: "to deliver", es: "librar" },
  { rank: 447, greek: "σάββατον", en: "Sabbath", es: "sábado" },
  { rank: 448, greek: "σάρξ", en: "flesh", es: "carne" },
  { rank: 449, greek: "σημεῖον", en: "sign", es: "señal" },
  { rank: 450, greek: "σήμερον", en: "today", es: "hoy" },
  { rank: 451, greek: "σιγάω", en: "to be silent", es: "callar" },
  { rank: 452, greek: "σῖτος", en: "wheat, food", es: "trigo" },
  { rank: 453, greek: "σιωπάω", en: "to be silent", es: "callar" },
  { rank: 454, greek: "σκάνδαλον", en: "stumbling block", es: "tropiezo" },
  { rank: 455, greek: "σκάπτω", en: "to dig", es: "cavar" },
  { rank: 456, greek: "σκηνή", en: "tent, tabernacle", es: "tabernáculo" },
  { rank: 457, greek: "σκιá", en: "shadow", es: "sombra" },
  { rank: 458, greek: "σκοτία", en: "darkness", es: "tinieblas" },
  { rank: 459, greek: "σκότος", en: "darkness", es: "oscuridad" },
  { rank: 460, greek: "σός", en: "your, yours", es: "tuyo" },
  { rank: 461, greek: "σοφία", en: "wisdom", es: "sabiduría" },
  { rank: 462, greek: "σοφός", en: "wise", es: "sabio" },
  { rank: 463, greek: "σπείρω", en: "to sow", es: "sembrar" },
  { rank: 464, greek: "σπέρμα", en: "seed", es: "semilla" },
  { rank: 465, greek: "σπλαγχνίζομαι", en: "to have compassion", es: "compadecerse" },
  { rank: 466, greek: "σπουδή", en: "haste, diligence", es: "prisa" },
  { rank: 467, greek: "σταυρός", en: "cross", es: "cruz" },
  { rank: 468, greek: "σταυρόω", en: "to crucify", es: "crucificar" },
  { rank: 469, greek: "στέφανος", en: "crown", es: "corona" },
  { rank: 470, greek: "στῆθος", en: "chest, breast", es: "pecho" },
  { rank: 471, greek: "στόμα", en: "mouth", es: "boca" },
  { rank: 472, greek: "στρατιώτης", en: "soldier", es: "soldado" },
  { rank: 473, greek: "σύ", en: "you", es: "tú" },
  { rank: 474, greek: "συγγενής", en: "relative", es: "pariente" },
  { rank: 475, greek: "συκῆ", en: "fig tree", es: "higuera" },
  { rank: 476, greek: "σύκον", en: "fig", es: "higo" },
  { rank: 477, greek: "συλλαμβάνω", en: "to seize, conceive", es: "prender" },
  { rank: 478, greek: "συμφέρω", en: "to be useful", es: "convenir" },
  { rank: 479, greek: "σύν", en: "with", es: "con" },
  { rank: 480, greek: "συνάγω", en: "to gather together", es: "reunir" },
  { rank: 481, greek: "συναγωγή", en: "synagogue", es: "sinagoga" },
  { rank: 482, greek: "σύνδουλος", en: "fellow slave", es: "consiervo" },
  { rank: 483, greek: "συνέρχομαι", en: "to come together", es: "reunirse" },
  { rank: 484, greek: "συνείδησις", en: "conscience", es: "conciencia" },
  { rank: 485, greek: "συνίημι", en: "to understand", es: "entender" },
  { rank: 486, greek: "συντέλεια", en: "completion, end", es: "fin" },
  { rank: 487, greek: "σφραγίς", en: "seal", es: "sello" },
  { rank: 488, greek: "σφραγίζω", en: "to seal", es: "sellar" },
  { rank: 489, greek: "σχίμα", en: "form, appearance", es: "apariencia" },
  { rank: 490, greek: "σώζω", en: "to save", es: "salvar" },
  { rank: 491, greek: "σῶμα", en: "body", es: "cuerpo" },
  { rank: 492, greek: "σωτήρ", en: "savior", es: "salvador" },
  { rank: 493, greek: "σωτηρία", en: "salvation", es: "salvación" },
  { rank: 494, greek: "ταπεινός", en: "humble", es: "humilde" },
  { rank: 495, greek: "ταράσσω", en: "to trouble", es: "turbar" },
  { rank: 496, greek: "ταχέως", en: "quickly", es: "pronto" },
  { rank: 497, greek: "τέκνον", en: "child", es: "hijo" },
  { rank: 498, greek: "τέλειος", en: "perfect, complete", es: "perfecto" },
  { rank: 499, greek: "τελειόω", en: "to complete", es: "perfeccionar" },
  { rank: 500, greek: "τέλος", en: "end, goal", es: "fin" },
].map(w => ({ ...w, greek: w.greek.normalize("NFC") }));
